POST http://localhost:9080/register HTTP/1.1
Content-Type: application/json

{
    "name": "Raghaav",
    "password": "raghav123",
    "email": "raghav12@exam566ple.com",
    "username": "raghav116623"
}

###

POST http://localhost:9080/register HTTP/1.1
Content-Type: application/json

{
    "name": "Raghaavan",
    "password": "raghavan123",
    "email": "raghav12an@exam566ple.com",
    "username": "raghavan116623"
}

###

POST http://localhost:9080/login HTTP/1.1
Content-type: application/json

{
    "email": "raghav12@exam566ple.com",
    "password": "raghav123"
}


###
GET http://localhost:9080/get_user_and_profile 
Content-type: application/json

{
    "token" :  "2c7a76f31ea86f500e5a6e15d0cacc4d441113aa7cee7ba65b134fc26833e41f"
}

###

POST http://localhost:9080/update_profile_data HTTP/1.1
Content-Type: application/json

{
  "token": "765399b1dc6696b0e2ab0dccaa06df3dad4c184ab03d23496c608a7ba398e52c",
  "bio": "Software developer with experience in building scalable web applications and user-focused digital solutions. Passionate about clean code, performance, and continuous learning. Enjoys turning complex problems into simple, reliable products while collaborating with teams to deliver real business impact.",
  "currentPost": "CTO",
  "pastWork": [
    {
      "company": "Google",
      "position": "CTO",
      "years": "2+"
    }
  ],
  "education": [
    {
      "school": "IIIT",
      "degree": "B.Tech",
      "fieldOfStudy": "2015-2019"
    }
  ]
}


### 
GET http://localhost:9080/users/get_all_users
